# Generated by Django 5.1.4 on 2026-05-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bid_increment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_make_offer_enabled', models.BooleanField(default=False)),
                ('buy_it_now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auction_type', models.CharField(choices=[('regular', 'Regular'), ('buy_it_now', 'Buy It Now'), ('sealed_bid', 'Sealed Bid')], max_length=20)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_description', models.TextField(blank=True, null=True)),
                ('global_notified', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('sold', 'Sold'), ('stopped', 'Stopped')], default='active', max_length=10)),
                ('is_relisted', models.BooleanField(default=False)),
                ('relist_notified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auctions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auction_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuctionWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('win_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auction_winners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('card_holder', models.CharField(max_length=255)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('bank_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bank_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_proxy', models.BooleanField(default=False)),
                ('proxy_max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'bids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiddingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_winner', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bidding_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blocked_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_paths', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback_replies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=50)),
                ('platform_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Transferred', 'Transferred')], default='Pending', max_length=15)),
                ('distribution_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fund_distribution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=10)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reminder_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regular_auction_limit', models.IntegerField()),
                ('sealed_bid_limit', models.IntegerField()),
                ('wallet_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'membership_plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('second_winner_offer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_status', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.CharField(default='Pending', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('shipping_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_notification_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=36, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debit_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('debit_card_expiry', models.CharField(blank=True, max_length=10, null=True)),
                ('debit_card_cvc', models.CharField(blank=True, max_length=4, null=True)),
                ('credit_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_card_expiry', models.CharField(blank=True, max_length=10, null=True)),
                ('credit_card_cvc', models.CharField(blank=True, max_length=4, null=True)),
                ('paypal_email', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_routing_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('premium_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'payment_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_type', models.CharField(choices=[('regular', 'Regular'), ('sealed_bid', 'Sealed Bid'), ('buy_now', 'Buy Now')], max_length=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'platform_commission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PremiumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_start_date', models.DateTimeField()),
                ('premium_end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'premium_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('report_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reported_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('reasons', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SealedBidDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_selection_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'sealed_bid_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellerPayout',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=50)),
                ('payout_status', models.CharField(default='Pending', max_length=20)),
                ('payout_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seller_payouts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('shipping_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shipping_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=5)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('bidding_restricted', models.BooleanField(default=False)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('paypal_email', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('membership_plan_id', models.IntegerField(blank=True, null=True)),
                ('premium', models.BooleanField(default=False)),
                ('account_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('banned', 'Banned')], default='pending', max_length=20)),
                ('id_proof', models.CharField(blank=True, max_length=255, null=True)),
                ('restriction_notified', models.BooleanField(default=False)),
                ('selfie', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_otp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'watchlist',
                'managed': False,
            },
        ),
    ]
